name = "chesapeake_shell"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "shellandbrush-test"
database_id = "f722d8e9a386cc043646124e71f223b9"
preview_database_id = "f722d8e9a386cc043646124e71f223b9"
